name: Upload Artifact Demo

on:
  push:
    branches: [ main ]

jobs:
  artifact-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Create demo file
        run: |
          mkdir -p artifact-folder
          echo "Marketplace Action demo file" > artifact-folder/assignment.txt

      - name: Upload file using marketplace action
        uses:
